### PR TITLE
scripts/vsmlrt.py: update esrgan janai models

### PR DESCRIPTION
**Pull request by hooke007**
Remove old models and add v2 ones

[models-1.zip](https://github.com/AmusementClub/vs-mlrt/files/11846403/models-1.zip)
AnimeJaNai_v2 : `RealESRGANv2\{animejanaiV2L1, animejanaiV2L2, animejanaiV2L3}.onnx`

### CODE REVIEW

**Comment by WolframRhodium** [comment]
Thanks! Could you explain why backward compatibility is not preserved?

**Comment by hooke007** [comment]
Do you mean "why remove old models"?
New models fix defects in old ones, I do not think keeping the old ones is a good idea.

**Comment by WolframRhodium** [comment]
What about starting the value of `animejanaiV2` from 5005?

**Comment by hooke007** [comment]
Hmm, and leave the 5000-5004 empty?

**Comment by WolframRhodium** [comment]
Yep.

**Comment by WolframRhodium** [comment]
Thanks!

**Comment by Ironclad17** [comment]
So what are the differences between L1, L2; L3? Do they correspond to Compact, UltraCompact; SuperUltraCompact respectively?

**Comment by hooke007** [comment]
L1 → fp32 SuperUltraCompact
L3 → fp32 Compact

**Pull request merged**
